### ISSUE TITLE
Unexpected token o error.

### ISSUE THREAD

**Issue by bajeeshe** [shutterstock/bigstock-node-client#2]
I am trying to use  bigstock-node-client , but iam getting the following bug.

SyntaxError: Unexpected token o
    at Object.parse (native)
    at new Category (E:\August2005\Source\DigitalOfficePro\Pixelfy\pixelfy_webap
p\node_modules\bigstock-node-client\lib\bigstock-client-node.js:266:31)

My calling code.
-------------------------------------------------------------------------------
bs.category({ language: 'en' }).then(function(Category) {
	console.log("Cats "+Category.toJSON());
});

**Comment by RichardLitt** [comment]
Hey @bajeeshe. Good point!

It looks like `	var result = response ? JSON.parse(response) : null;` is parsing an object occasionally. I have submitted a patch in #7 - want to test it and see if it works?

**Comment by RichardLitt** [comment]
@bajeeshe This should be fixed now!
