### ISSUE TITLE
Publish changes to npm

### ISSUE THREAD

**Issue by RichardLitt** [shutterstock/bigstock-node-client#6]
@tlackemann are you still interested in maintaining this repository? Can you transfer publishing rights to this repo on npm? `npm owner add shutterstock` should do it.

Let me know. Thank you!

**Comment by tlackemann** [comment]
Hey @RichardLitt, I'm not interested in maintaining but I can transfer ownership quite easily.

I tried running the command you gave but received this error. Open to thoughts

```
npm ERR! Maintainer should have an email: {"name":"shutterstock"} : bigstock-node-client
```

**Comment by RichardLitt** [comment]
Try `sstk-admin`, if you could. Thank you!

**Comment by tlackemann** [comment]
Cool, that worked! You should have access.

Feel free to remove or keep me on or whatever you wish to do :) Thanks!

**Comment by RichardLitt** [comment]
Sounds good - thank you! I sent you an email to keep the chatter off of these issues. Thanks again.
